# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       harbour-machines-vs-machines-sfos

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    Machines vs. Machines
Version:    1.3.3
Release:    1
Group:      Qt/Qt
License:    GPLv3
URL:        https://github.com/mzanetti/machines-vs-machines-sfos
Source0:    %{name}-%{version}.tar.bz2
Requires:   sailfishsilica-qt5 >= 0.10.9
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  desktop-file-utils
BuildRequires:  qt5-qttools-linguist

%description
A Game of Machine VS Machine forked from https://github.com/mzanetti/machines-vs-machines-sfos

%if "%{?vendor}" == "chum"
PackageName: Machines vs. Machines
Type: desktop-application
Categories:
 - Game
PackagerName: Mark Washeim (poetaster)
DeveloperName: Michael Zanetti
Custom:
  Repo: https://github.com/mzanetti/machines-vs-machines-sfos
  PackagingRepo: https://github.com/poetaster/machines-vs-machines-sfos
Icon: https://github.com/mzanetti/machines-vs-machines-sfos/raw/master/icons/256x256/harbour-machines-vs-machines-sfos.png
Screenshots:
 - https://raw.githubusercontent.com/poetaster/machines-vs-machines-sfos/master/screen-1.png
 - https://raw.githubusercontent.com/poetaster/machines-vs-machines-sfos/master/screen-2.png
 - https://raw.githubusercontent.com/poetaster/machines-vs-machines-sfos/master/screen-3.png
 - https://raw.githubusercontent.com/poetaster/machines-vs-machines-sfos/master/screen-4.png
Url:
  Help: https://github.com/poetaster/machines-vs-machines-sfos/discussions
  Bugtracker:https://github.com/mzanetti/machines-vs-machines-sfos/issues
  Donation: https://www.paypal.com/donate/?cmd=_s-xclick&hosted_button_id=USWAUUU2MD9Z4
%endif

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
# >> files
# << files
